import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'pt' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'nav.features': 'Features',
    'nav.prices': 'Prices',
    'nav.testimonials': 'Testimonials',
    'nav.startTrading': 'Start Trading',
    'hero.badge': 'Next-gen crypto trading platform',
    'hero.title1': 'Trade crypto with',
    'hero.title2': 'confidence & security',
    'hero.description': 'Experience seamless cryptocurrency trading with advanced features, real-time analytics, and institutional-grade security.',
    'hero.startNow': 'Start Trading Now',
    'hero.viewMarkets': 'View Markets',
    'features.title1': 'Advanced Trading',
    'features.title2': 'Features & Tools',
    'features.description': 'Experience professional-grade trading tools and features designed for both novice and experienced crypto traders.',
    'pricing.title1': 'Choose Your',
    'pricing.title2': 'Trading Plan',
    'pricing.description': 'Select the perfect trading plan with advanced features and competitive fees',
    'cta.title': 'Ready to start trading?',
    'cta.description': 'Join thousands of traders who have already discovered the power of our platform.',
    'cta.button': 'Create Account',
    'pricing.basic.name': 'Basic Trader',
    'pricing.basic.description': 'Perfect for beginners starting their crypto journey',
    'pricing.pro.name': 'Pro Trader',
    'pricing.pro.description': 'Advanced features for serious traders',
    'pricing.institutional.name': 'Institutional',
    'pricing.institutional.description': 'Enterprise-grade solutions for institutions',
    'pricing.popular': 'Most Popular',
    'pricing.startTrading': 'Start Trading',
    'pricing.basic.feature1': 'Basic spot trading',
    'pricing.basic.feature2': 'Market & limit orders',
    'pricing.basic.feature3': 'Basic market analysis',
    'pricing.basic.feature4': 'Email support',
    'pricing.pro.feature1': 'Advanced trading tools',
    'pricing.pro.feature2': 'Margin trading up to 10x',
    'pricing.pro.feature3': 'Advanced technical analysis',
    'pricing.pro.feature4': 'Priority support',
    'pricing.pro.feature5': 'API access',
    'pricing.institutional.feature1': 'Custom trading solutions',
    'pricing.institutional.feature2': 'Unlimited trading volume',
    'pricing.institutional.feature3': 'OTC desk access',
    'pricing.institutional.feature4': 'Dedicated account manager',
    'pricing.institutional.feature5': 'Custom API integration',
    'pricing.institutional.feature6': '24/7 priority support',
    'testimonials.title': 'Trusted by Traders',
    'testimonials.subtitle': 'Join thousands of satisfied traders on CryptoTrade',
    'testimonials.michael.role': 'Professional Trader',
    'testimonials.michael.content': 'The real-time market data and advanced trading features have significantly improved my trading performance. The platform\'s security measures give me peace of mind.',
    'testimonials.sarah.role': 'Crypto Fund Manager',
    'testimonials.sarah.content': 'CryptoTrade\'s institutional-grade tools have transformed our trading strategy. The API integration and automated features have saved us countless hours.',
    'testimonials.david.role': 'Early Crypto Investor',
    'testimonials.david.content': 'The customer support is exceptional, and the platform\'s intuitive design made getting started with crypto trading seamless. A game-changer for both beginners and pros.',
    'testimonials.emily.role': 'DeFi Developer',
    'testimonials.emily.content': 'We\'ve seen remarkable improvements in our trading efficiency since switching to CryptoTrade. The smart order routing and liquidity aggregation are particularly impressive.',
    'testimonials.james.role': 'Crypto Security Expert',
    'testimonials.james.content': 'The security features are robust and the regular updates keep us ahead of emerging threats. It\'s exactly what the crypto industry needed.',
    'testimonials.lisa.role': 'Portfolio Manager',
    'testimonials.lisa.content': 'The platform\'s ability to handle complex trading strategies while maintaining simplicity in its interface is remarkable. It\'s been invaluable for our portfolio management.',
    'signup.backToHome': 'Back to Home',
    'signup.title': 'Create Your Account',
    'signup.subtitle': 'Join thousands of traders on CryptoTrade',
    'signup.firstName': 'First Name',
    'signup.lastName': 'Last Name',
    'signup.email': 'Email',
    'signup.password': 'Password',
    'signup.firstNamePlaceholder': 'Enter your first name',
    'signup.lastNamePlaceholder': 'Enter your last name',
    'signup.emailPlaceholder': 'Enter your email',
    'signup.passwordPlaceholder': 'Create a strong password',
    'signup.createAccount': 'Create Account',
    'signup.alreadyHaveAccount': 'Already have an account?',
    'signup.signIn': 'Sign In',
    'login.backToHome': 'Back to Home',
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to your CryptoTrade account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.emailPlaceholder': 'Enter your email',
    'login.passwordPlaceholder': 'Enter your password',
    'login.forgotPassword': 'Forgot password?',
    'login.signIn': 'Sign In',
    'login.noAccount': 'Don\'t have an account?',
    'login.createAccount': 'Create Account',
    'markets.backToHome': 'Back to Home',
    'markets.title': 'Crypto',
    'markets.titleHighlight': 'Markets',
    'markets.subtitle': 'Real-time cryptocurrency prices and market data',
    'markets.searchPlaceholder': 'Search cryptocurrencies...',
    'markets.coin': 'Coin',
    'markets.price': 'Price',
    'markets.change24h': '24h Change',
    'markets.volume': 'Volume',
    'markets.marketCap': 'Market Cap',
    'markets.action': 'Action',
    'markets.trade': 'Trade',
    'markets.ctaTitle': 'Ready to start trading?',
    'markets.ctaDescription': 'Join thousands of traders and start your crypto journey today',
    'markets.startTrading': 'Start Trading Now'
  },
  es: {
    'nav.features': 'Características',
    'nav.prices': 'Precios',
    'nav.testimonials': 'Testimonios',
    'nav.startTrading': 'Comenzar a Operar',
    'hero.badge': 'Plataforma de trading crypto de nueva generación',
    'hero.title1': 'Opera criptomonedas con',
    'hero.title2': 'confianza y seguridad',
    'hero.description': 'Experimenta el trading de criptomonedas sin problemas con características avanzadas, análisis en tiempo real y seguridad de nivel institucional.',
    'hero.startNow': 'Comenzar Ahora',
    'hero.viewMarkets': 'Ver Mercados',
    'features.title1': 'Trading Avanzado',
    'features.title2': 'Características y Herramientas',
    'features.description': 'Experimenta herramientas y características de trading de nivel profesional diseñadas tanto para traders novatos como experimentados.',
    'pricing.title1': 'Elige Tu',
    'pricing.title2': 'Plan de Trading',
    'pricing.description': 'Selecciona el plan de trading perfecto con características avanzadas y tarifas competitivas',
    'cta.title': '¿Listo para comenzar a operar?',
    'cta.description': 'Únete a miles de traders que ya han descubierto el poder de nuestra plataforma.',
    'cta.button': 'Crear Cuenta',
    'pricing.basic.name': 'Trader Básico',
    'pricing.basic.description': 'Perfecto para principiantes que comienzan su viaje crypto',
    'pricing.pro.name': 'Trader Pro',
    'pricing.pro.description': 'Características avanzadas para traders serios',
    'pricing.institutional.name': 'Institucional',
    'pricing.institutional.description': 'Soluciones de nivel empresarial para instituciones',
    'pricing.popular': 'Más Popular',
    'pricing.startTrading': 'Comenzar a Operar',
    'pricing.basic.feature1': 'Trading spot básico',
    'pricing.basic.feature2': 'Órdenes de mercado y límite',
    'pricing.basic.feature3': 'Análisis de mercado básico',
    'pricing.basic.feature4': 'Soporte por email',
    'pricing.pro.feature1': 'Herramientas de trading avanzadas',
    'pricing.pro.feature2': 'Trading con margen hasta 10x',
    'pricing.pro.feature3': 'Análisis técnico avanzado',
    'pricing.pro.feature4': 'Soporte prioritario',
    'pricing.pro.feature5': 'Acceso a API',
    'pricing.institutional.feature1': 'Soluciones de trading personalizadas',
    'pricing.institutional.feature2': 'Volumen de trading ilimitado',
    'pricing.institutional.feature3': 'Acceso a mesa OTC',
    'pricing.institutional.feature4': 'Gerente de cuenta dedicado',
    'pricing.institutional.feature5': 'Integración API personalizada',
    'pricing.institutional.feature6': 'Soporte prioritario 24/7',
    'testimonials.title': 'Confiado por Traders',
    'testimonials.subtitle': 'Únete a miles de traders satisfechos en CryptoTrade',
    'testimonials.michael.role': 'Trader Profesional',
    'testimonials.michael.content': 'Los datos de mercado en tiempo real y las características de trading avanzadas han mejorado significativamente mi rendimiento. Las medidas de seguridad de la plataforma me dan tranquilidad.',
    'testimonials.sarah.role': 'Gerente de Fondo Crypto',
    'testimonials.sarah.content': 'Las herramientas de nivel institucional de CryptoTrade han transformado nuestra estrategia de trading. La integración API y las características automatizadas nos han ahorrado incontables horas.',
    'testimonials.david.role': 'Inversor Crypto Temprano',
    'testimonials.david.content': 'El soporte al cliente es excepcional, y el diseño intuitivo de la plataforma hizo que comenzar con el trading crypto fuera perfecto. Un cambio radical para principiantes y profesionales.',
    'testimonials.emily.role': 'Desarrolladora DeFi',
    'testimonials.emily.content': 'Hemos visto mejoras notables en nuestra eficiencia de trading desde cambiar a CryptoTrade. El enrutamiento inteligente de órdenes y la agregación de liquidez son particularmente impresionantes.',
    'testimonials.james.role': 'Experto en Seguridad Crypto',
    'testimonials.james.content': 'Las características de seguridad son robustas y las actualizaciones regulares nos mantienen adelante de las amenazas emergentes. Es exactamente lo que la industria crypto necesitaba.',
    'testimonials.lisa.role': 'Gerente de Portafolio',
    'testimonials.lisa.content': 'La capacidad de la plataforma para manejar estrategias de trading complejas mientras mantiene simplicidad en su interfaz es notable. Ha sido invaluable para nuestro manejo de portafolio.',
    'signup.backToHome': 'Volver al Inicio',
    'signup.title': 'Crea Tu Cuenta',
    'signup.subtitle': 'Únete a miles de traders en CryptoTrade',
    'signup.firstName': 'Nombre',
    'signup.lastName': 'Apellido',
    'signup.email': 'Correo Electrónico',
    'signup.password': 'Contraseña',
    'signup.firstNamePlaceholder': 'Ingresa tu nombre',
    'signup.lastNamePlaceholder': 'Ingresa tu apellido',
    'signup.emailPlaceholder': 'Ingresa tu correo',
    'signup.passwordPlaceholder': 'Crea una contraseña segura',
    'signup.createAccount': 'Crear Cuenta',
    'signup.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'signup.signIn': 'Iniciar Sesión',
    'login.backToHome': 'Volver al Inicio',
    'login.title': 'Bienvenido de Vuelta',
    'login.subtitle': 'Inicia sesión en tu cuenta de CryptoTrade',
    'login.email': 'Correo Electrónico',
    'login.password': 'Contraseña',
    'login.emailPlaceholder': 'Ingresa tu correo',
    'login.passwordPlaceholder': 'Ingresa tu contraseña',
    'login.forgotPassword': '¿Olvidaste tu contraseña?',
    'login.signIn': 'Iniciar Sesión',
    'login.noAccount': '¿No tienes una cuenta?',
    'login.createAccount': 'Crear Cuenta',
    'markets.backToHome': 'Volver al Inicio',
    'markets.title': 'Mercados',
    'markets.titleHighlight': 'Crypto',
    'markets.subtitle': 'Precios de criptomonedas y datos de mercado en tiempo real',
    'markets.searchPlaceholder': 'Buscar criptomonedas...',
    'markets.coin': 'Moneda',
    'markets.price': 'Precio',
    'markets.change24h': 'Cambio 24h',
    'markets.volume': 'Volumen',
    'markets.marketCap': 'Cap. Mercado',
    'markets.action': 'Acción',
    'markets.trade': 'Operar',
    'markets.ctaTitle': '¿Listo para comenzar a operar?',
    'markets.ctaDescription': 'Únete a miles de traders y comienza tu viaje crypto hoy',
    'markets.startTrading': 'Comenzar a Operar'
  },
  fr: {
    'nav.features': 'Fonctionnalités',
    'nav.prices': 'Prix',
    'nav.testimonials': 'Témoignages',
    'nav.startTrading': 'Commencer à Trader',
    'hero.badge': 'Plateforme de trading crypto nouvelle génération',
    'hero.title1': 'Tradez les cryptos avec',
    'hero.title2': 'confiance et sécurité',
    'hero.description': 'Découvrez le trading de cryptomonnaies fluide avec des fonctionnalités avancées, des analyses en temps réel et une sécurité de niveau institutionnel.',
    'hero.startNow': 'Commencer Maintenant',
    'hero.viewMarkets': 'Voir les Marchés',
    'features.title1': 'Trading Avancé',
    'features.title2': 'Fonctionnalités et Outils',
    'features.description': 'Découvrez des outils et fonctionnalités de trading de niveau professionnel conçus pour les traders novices et expérimentés.',
    'pricing.title1': 'Choisissez Votre',
    'pricing.title2': 'Plan de Trading',
    'pricing.description': 'Sélectionnez le plan de trading parfait avec des fonctionnalités avancées et des frais compétitifs',
    'cta.title': 'Prêt à commencer à trader?',
    'cta.description': 'Rejoignez des milliers de traders qui ont déjà découvert la puissance de notre plateforme.',
    'cta.button': 'Créer un Compte',
    'pricing.basic.name': 'Trader Basique',
    'pricing.basic.description': 'Parfait pour les débutants qui commencent leur parcours crypto',
    'pricing.pro.name': 'Trader Pro',
    'pricing.pro.description': 'Fonctionnalités avancées pour les traders sérieux',
    'pricing.institutional.name': 'Institutionnel',
    'pricing.institutional.description': 'Solutions de niveau entreprise pour les institutions',
    'pricing.popular': 'Le Plus Populaire',
    'pricing.startTrading': 'Commencer à Trader',
    'pricing.basic.feature1': 'Trading spot de base',
    'pricing.basic.feature2': 'Ordres au marché et à cours limité',
    'pricing.basic.feature3': 'Analyse de marché de base',
    'pricing.basic.feature4': 'Support par email',
    'pricing.pro.feature1': 'Outils de trading avancés',
    'pricing.pro.feature2': 'Trading sur marge jusqu\'à 10x',
    'pricing.pro.feature3': 'Analyse technique avancée',
    'pricing.pro.feature4': 'Support prioritaire',
    'pricing.pro.feature5': 'Accès API',
    'pricing.institutional.feature1': 'Solutions de trading personnalisées',
    'pricing.institutional.feature2': 'Volume de trading illimité',
    'pricing.institutional.feature3': 'Accès au bureau OTC',
    'pricing.institutional.feature4': 'Gestionnaire de compte dédié',
    'pricing.institutional.feature5': 'Intégration API personnalisée',
    'pricing.institutional.feature6': 'Support prioritaire 24/7',
    'testimonials.title': 'Approuvé par les Traders',
    'testimonials.subtitle': 'Rejoignez des milliers de traders satisfaits sur CryptoTrade',
    'testimonials.michael.role': 'Trader Professionnel',
    'testimonials.michael.content': 'Les données de marché en temps réel et les fonctionnalités de trading avancées ont considérablement amélioré mes performances. Les mesures de sécurité de la plateforme me rassurent.',
    'testimonials.sarah.role': 'Gestionnaire de Fonds Crypto',
    'testimonials.sarah.content': 'Les outils de niveau institutionnel de CryptoTrade ont transformé notre stratégie de trading. L\'intégration API et les fonctionnalités automatisées nous ont fait économiser d\'innombrables heures.',
    'testimonials.david.role': 'Investisseur Crypto Précoce',
    'testimonials.david.content': 'Le support client est exceptionnel, et le design intuitif de la plateforme a rendu le démarrage du trading crypto fluide. Un changement radical pour débutants et professionnels.',
    'testimonials.emily.role': 'Développeuse DeFi',
    'testimonials.emily.content': 'Nous avons vu des améliorations remarquables dans notre efficacité de trading depuis le passage à CryptoTrade. Le routage intelligent des ordres et l\'agrégation de liquidité sont particulièrement impressionnants.',
    'testimonials.james.role': 'Expert en Sécurité Crypto',
    'testimonials.james.content': 'Les fonctionnalités de sécurité sont robustes et les mises à jour régulières nous gardent en avance sur les menaces émergentes. C\'est exactement ce dont l\'industrie crypto avait besoin.',
    'testimonials.lisa.role': 'Gestionnaire de Portefeuille',
    'testimonials.lisa.content': 'La capacité de la plateforme à gérer des stratégies de trading complexes tout en maintenant la simplicité dans son interface est remarquable. Elle a été inestimable pour notre gestion de portefeuille.',
    'signup.backToHome': 'Retour à l\'Accueil',
    'signup.title': 'Créez Votre Compte',
    'signup.subtitle': 'Rejoignez des milliers de traders sur CryptoTrade',
    'signup.firstName': 'Prénom',
    'signup.lastName': 'Nom',
    'signup.email': 'Email',
    'signup.password': 'Mot de Passe',
    'signup.firstNamePlaceholder': 'Entrez votre prénom',
    'signup.lastNamePlaceholder': 'Entrez votre nom',
    'signup.emailPlaceholder': 'Entrez votre email',
    'signup.passwordPlaceholder': 'Créez un mot de passe fort',
    'signup.createAccount': 'Créer un Compte',
    'signup.alreadyHaveAccount': 'Vous avez déjà un compte?',
    'signup.signIn': 'Se Connecter',
    'login.backToHome': 'Retour à l\'Accueil',
    'login.title': 'Bon Retour',
    'login.subtitle': 'Connectez-vous à votre compte CryptoTrade',
    'login.email': 'Email',
    'login.password': 'Mot de Passe',
    'login.emailPlaceholder': 'Entrez votre email',
    'login.passwordPlaceholder': 'Entrez votre mot de passe',
    'login.forgotPassword': 'Mot de passe oublié?',
    'login.signIn': 'Se Connecter',
    'login.noAccount': 'Vous n\'avez pas de compte?',
    'login.createAccount': 'Créer un Compte',
    'markets.backToHome': 'Retour à l\'Accueil',
    'markets.title': 'Marchés',
    'markets.titleHighlight': 'Crypto',
    'markets.subtitle': 'Prix des cryptomonnaies et données de marché en temps réel',
    'markets.searchPlaceholder': 'Rechercher des cryptomonnaies...',
    'markets.coin': 'Monnaie',
    'markets.price': 'Prix',
    'markets.change24h': 'Variation 24h',
    'markets.volume': 'Volume',
    'markets.marketCap': 'Cap. Marché',
    'markets.action': 'Action',
    'markets.trade': 'Trader',
    'markets.ctaTitle': 'Prêt à commencer à trader?',
    'markets.ctaDescription': 'Rejoignez des milliers de traders et commencez votre parcours crypto aujourd\'hui',
    'markets.startTrading': 'Commencer à Trader'
  },
  de: {
    'nav.features': 'Funktionen',
    'nav.prices': 'Preise',
    'nav.testimonials': 'Testimonials',
    'nav.startTrading': 'Trading Starten',
    'hero.badge': 'Nächste Generation Krypto-Trading-Plattform',
    'hero.title1': 'Trade Krypto mit',
    'hero.title2': 'Vertrauen und Sicherheit',
    'hero.description': 'Erleben Sie nahtloses Kryptowährungs-Trading mit erweiterten Funktionen, Echtzeit-Analysen und institutioneller Sicherheit.',
    'hero.startNow': 'Jetzt Starten',
    'hero.viewMarkets': 'Märkte Anzeigen',
    'features.title1': 'Erweiterte Trading',
    'features.title2': 'Funktionen & Tools',
    'features.description': 'Erleben Sie professionelle Trading-Tools und -Funktionen für Anfänger und erfahrene Krypto-Trader.',
    'pricing.title1': 'Wählen Sie Ihren',
    'pricing.title2': 'Trading-Plan',
    'pricing.description': 'Wählen Sie den perfekten Trading-Plan mit erweiterten Funktionen und wettbewerbsfähigen Gebühren',
    'cta.title': 'Bereit zum Trading?',
    'cta.description': 'Schließen Sie sich Tausenden von Tradern an, die bereits die Macht unserer Plattform entdeckt haben.',
    'cta.button': 'Konto Erstellen',
    'pricing.basic.name': 'Basis Trader',
    'pricing.basic.description': 'Perfekt für Anfänger, die ihre Krypto-Reise beginnen',
    'pricing.pro.name': 'Pro Trader',
    'pricing.pro.description': 'Erweiterte Funktionen für ernsthafte Trader',
    'pricing.institutional.name': 'Institutionell',
    'pricing.institutional.description': 'Unternehmenslösungen für Institutionen',
    'pricing.popular': 'Am Beliebtesten',
    'pricing.startTrading': 'Trading Starten',
    'pricing.basic.feature1': 'Basis Spot-Trading',
    'pricing.basic.feature2': 'Markt- und Limit-Orders',
    'pricing.basic.feature3': 'Basis Marktanalyse',
    'pricing.basic.feature4': 'E-Mail Support',
    'pricing.pro.feature1': 'Erweiterte Trading-Tools',
    'pricing.pro.feature2': 'Margin-Trading bis zu 10x',
    'pricing.pro.feature3': 'Erweiterte technische Analyse',
    'pricing.pro.feature4': 'Prioritäts-Support',
    'pricing.pro.feature5': 'API-Zugang',
    'pricing.institutional.feature1': 'Maßgeschneiderte Trading-Lösungen',
    'pricing.institutional.feature2': 'Unbegrenztes Trading-Volumen',
    'pricing.institutional.feature3': 'OTC-Desk Zugang',
    'pricing.institutional.feature4': 'Dedizierter Account Manager',
    'pricing.institutional.feature5': 'Maßgeschneiderte API-Integration',
    'pricing.institutional.feature6': '24/7 Prioritäts-Support',
    'testimonials.title': 'Vertraut von Tradern',
    'testimonials.subtitle': 'Schließen Sie sich Tausenden zufriedener Trader auf CryptoTrade an',
    'testimonials.michael.role': 'Professioneller Trader',
    'testimonials.michael.content': 'Die Echtzeit-Marktdaten und erweiterten Trading-Funktionen haben meine Trading-Performance erheblich verbessert. Die Sicherheitsmaßnahmen der Plattform geben mir Seelenfrieden.',
    'testimonials.sarah.role': 'Krypto-Fondsmanagerin',
    'testimonials.sarah.content': 'CryptoTrades institutionelle Tools haben unsere Trading-Strategie transformiert. Die API-Integration und automatisierten Funktionen haben uns unzählige Stunden gespart.',
    'testimonials.david.role': 'Früher Krypto-Investor',
    'testimonials.david.content': 'Der Kundensupport ist außergewöhnlich, und das intuitive Design der Plattform machte den Einstieg ins Krypto-Trading nahtlos. Ein Wendepunkt für Anfänger und Profis.',
    'testimonials.emily.role': 'DeFi-Entwicklerin',
    'testimonials.emily.content': 'Wir haben bemerkenswerte Verbesserungen in unserer Trading-Effizienz seit dem Wechsel zu CryptoTrade gesehen. Das intelligente Order-Routing und die Liquiditätsaggregation sind besonders beeindruckend.',
    'testimonials.james.role': 'Krypto-Sicherheitsexperte',
    'testimonials.james.content': 'Die Sicherheitsfunktionen sind robust und die regelmäßigen Updates halten uns den aufkommenden Bedrohungen voraus. Es ist genau das, was die Krypto-Industrie brauchte.',
    'testimonials.lisa.role': 'Portfolio-Managerin',
    'testimonials.lisa.content': 'Die Fähigkeit der Plattform, komplexe Trading-Strategien zu handhaben und dabei die Einfachheit in der Benutzeroberfläche zu bewahren, ist bemerkenswert. Sie war unbezahlbar für unser Portfolio-Management.',
    'signup.backToHome': 'Zurück zur Startseite',
    'signup.title': 'Erstellen Sie Ihr Konto',
    'signup.subtitle': 'Schließen Sie sich Tausenden von Tradern auf CryptoTrade an',
    'signup.firstName': 'Vorname',
    'signup.lastName': 'Nachname',
    'signup.email': 'E-Mail',
    'signup.password': 'Passwort',
    'signup.firstNamePlaceholder': 'Geben Sie Ihren Vornamen ein',
    'signup.lastNamePlaceholder': 'Geben Sie Ihren Nachnamen ein',
    'signup.emailPlaceholder': 'Geben Sie Ihre E-Mail ein',
    'signup.passwordPlaceholder': 'Erstellen Sie ein starkes Passwort',
    'signup.createAccount': 'Konto Erstellen',
    'signup.alreadyHaveAccount': 'Haben Sie bereits ein Konto?',
    'signup.signIn': 'Anmelden',
    'login.backToHome': 'Zurück zur Startseite',
    'login.title': 'Willkommen zurück',
    'login.subtitle': 'Melden Sie sich bei Ihrem CryptoTrade-Konto an',
    'login.email': 'E-Mail',
    'login.password': 'Passwort',
    'login.emailPlaceholder': 'Geben Sie Ihre E-Mail ein',
    'login.passwordPlaceholder': 'Geben Sie Ihr Passwort ein',
    'login.forgotPassword': 'Passwort vergessen?',
    'login.signIn': 'Anmelden',
    'login.noAccount': 'Haben Sie kein Konto?',
    'login.createAccount': 'Konto Erstellen',
    'markets.backToHome': 'Zurück zur Startseite',
    'markets.title': 'Krypto',
    'markets.titleHighlight': 'Märkte',
    'markets.subtitle': 'Echtzeit-Kryptowährungspreise und Marktdaten',
    'markets.searchPlaceholder': 'Kryptowährungen suchen...',
    'markets.coin': 'Münze',
    'markets.price': 'Preis',
    'markets.change24h': '24h Änderung',
    'markets.volume': 'Volumen',
    'markets.marketCap': 'Marktkapitalisierung',
    'markets.action': 'Aktion',
    'markets.trade': 'Handeln',
    'markets.ctaTitle': 'Bereit zum Trading?',
    'markets.ctaDescription': 'Schließen Sie sich Tausenden von Tradern an und beginnen Sie heute Ihre Krypto-Reise',
    'markets.startTrading': 'Jetzt Trading Starten'
  },
  pt: {
    'nav.features': 'Recursos',
    'nav.prices': 'Preços',
    'nav.testimonials': 'Depoimentos',
    'nav.startTrading': 'Começar a Negociar',
    'hero.badge': 'Plataforma de trading crypto de nova geração',
    'hero.title1': 'Negocie crypto com',
    'hero.title2': 'confiança e segurança',
    'hero.description': 'Experimente trading de criptomoedas perfeito com recursos avançados, análises em tempo real e segurança de nível institucional.',
    'hero.startNow': 'Começar Agora',
    'hero.viewMarkets': 'Ver Mercados',
    'features.title1': 'Trading Avançado',
    'features.title2': 'Recursos e Ferramentas',
    'features.description': 'Experimente ferramentas e recursos de trading de nível profissional projetados para traders iniciantes e experientes.',
    'pricing.title1': 'Escolha Seu',
    'pricing.title2': 'Plano de Trading',
    'pricing.description': 'Selecione o plano de trading perfeito com recursos avançados e taxas competitivas',
    'cta.title': 'Pronto para começar a negociar?',
    'cta.description': 'Junte-se a milhares de traders que já descobriram o poder da nossa plataforma.',
    'cta.button': 'Criar Conta',
    'pricing.basic.name': 'Trader Básico',
    'pricing.basic.description': 'Perfeito para iniciantes começando sua jornada crypto',
    'pricing.pro.name': 'Trader Pro',
    'pricing.pro.description': 'Recursos avançados para traders sérios',
    'pricing.institutional.name': 'Institucional',
    'pricing.institutional.description': 'Soluções empresariais para instituições',
    'pricing.popular': 'Mais Popular',
    'pricing.startTrading': 'Começar a Negociar',
    'pricing.basic.feature1': 'Trading spot básico',
    'pricing.basic.feature2': 'Ordens de mercado e limite',
    'pricing.basic.feature3': 'Análise de mercado básica',
    'pricing.basic.feature4': 'Suporte por email',
    'pricing.pro.feature1': 'Ferramentas de trading avançadas',
    'pricing.pro.feature2': 'Trading com margem até 10x',
    'pricing.pro.feature3': 'Análise técnica avançada',
    'pricing.pro.feature4': 'Suporte prioritário',
    'pricing.pro.feature5': 'Acesso à API',
    'pricing.institutional.feature1': 'Soluções de trading personalizadas',
    'pricing.institutional.feature2': 'Volume de trading ilimitado',
    'pricing.institutional.feature3': 'Acesso à mesa OTC',
    'pricing.institutional.feature4': 'Gerente de conta dedicado',
    'pricing.institutional.feature5': 'Integração API personalizada',
    'pricing.institutional.feature6': 'Suporte prioritário 24/7',
    'testimonials.title': 'Confiado por Traders',
    'testimonials.subtitle': 'Junte-se a milhares de traders satisfeitos no CryptoTrade',
    'testimonials.michael.role': 'Trader Profissional',
    'testimonials.michael.content': 'Os dados de mercado em tempo real e recursos de trading avançados melhoraram significativamente meu desempenho. As medidas de segurança da plataforma me dão tranquilidade.',
    'testimonials.sarah.role': 'Gerente de Fundo Crypto',
    'testimonials.sarah.content': 'As ferramentas de nível institucional do CryptoTrade transformaram nossa estratégia de trading. A integração API e recursos automatizados nos pouparam inúmeras horas.',
    'testimonials.david.role': 'Investidor Crypto Inicial',
    'testimonials.david.content': 'O suporte ao cliente é excepcional, e o design intuitivo da plataforma tornou o início do trading crypto perfeito. Uma mudança radical para iniciantes e profissionais.',
    'testimonials.emily.role': 'Desenvolvedora DeFi',
    'testimonials.emily.content': 'Vimos melhorias notáveis em nossa eficiência de trading desde a mudança para o CryptoTrade. O roteamento inteligente de ordens e agregação de liquidez são particularmente impressionantes.',
    'testimonials.james.role': 'Especialista em Segurança Crypto',
    'testimonials.james.content': 'Os recursos de segurança são robustos e as atualizações regulares nos mantêm à frente das ameaças emergentes. É exatamente o que a indústria crypto precisava.',
    'testimonials.lisa.role': 'Gerente de Portfólio',
    'testimonials.lisa.content': 'A capacidade da plataforma de lidar com estratégias de trading complexas mantendo simplicidade em sua interface é notável. Foi inestimável para nosso gerenciamento de portfólio.',
    'signup.backToHome': 'Voltar ao Início',
    'signup.title': 'Crie Sua Conta',
    'signup.subtitle': 'Junte-se a milhares de traders no CryptoTrade',
    'signup.firstName': 'Nome',
    'signup.lastName': 'Sobrenome',
    'signup.email': 'Email',
    'signup.password': 'Senha',
    'signup.firstNamePlaceholder': 'Digite seu nome',
    'signup.lastNamePlaceholder': 'Digite seu sobrenome',
    'signup.emailPlaceholder': 'Digite seu email',
    'signup.passwordPlaceholder': 'Crie uma senha forte',
    'signup.createAccount': 'Criar Conta',
    'signup.alreadyHaveAccount': 'Já tem uma conta?',
    'signup.signIn': 'Entrar',
    'login.backToHome': 'Voltar ao Início',
    'login.title': 'Bem-vindo de Volta',
    'login.subtitle': 'Entre na sua conta CryptoTrade',
    'login.email': 'Email',
    'login.password': 'Senha',
    'login.emailPlaceholder': 'Digite seu email',
    'login.passwordPlaceholder': 'Digite sua senha',
    'login.forgotPassword': 'Esqueceu a senha?',
    'login.signIn': 'Entrar',
    'login.noAccount': 'Não tem uma conta?',
    'login.createAccount': 'Criar Conta',
    'markets.backToHome': 'Voltar ao Início',
    'markets.title': 'Mercados',
    'markets.titleHighlight': 'Crypto',
    'markets.subtitle': 'Preços de criptomoedas e dados de mercado em tempo real',
    'markets.searchPlaceholder': 'Pesquisar criptomoedas...',
    'markets.coin': 'Moeda',
    'markets.price': 'Preço',
    'markets.change24h': 'Mudança 24h',
    'markets.volume': 'Volume',
    'markets.marketCap': 'Cap. Mercado',
    'markets.action': 'Ação',
    'markets.trade': 'Negociar',
    'markets.ctaTitle': 'Pronto para começar a negociar?',
    'markets.ctaDescription': 'Junte-se a milhares de traders e comece sua jornada crypto hoje',
    'markets.startTrading': 'Começar a Negociar'
  },
  ja: {
    'nav.features': '機能',
    'nav.prices': '価格',
    'nav.testimonials': 'お客様の声',
    'nav.startTrading': '取引開始',
    'hero.badge': '次世代暗号通貨取引プラットフォーム',
    'hero.title1': '暗号通貨を取引する',
    'hero.title2': '信頼と安全性',
    'hero.description': '高度な機能、リアルタイム分析、機関レベルのセキュリティでシームレスな暗号通貨取引を体験してください。',
    'hero.startNow': '今すぐ開始',
    'hero.viewMarkets': 'マーケットを見る',
    'features.title1': '高度な取引',
    'features.title2': '機能とツール',
    'features.description': '初心者から経験豊富な暗号通貨トレーダーまで、プロフェッショナルレベルの取引ツールと機能を体験してください。',
    'pricing.title1': 'あなたの',
    'pricing.title2': '取引プランを選択',
    'pricing.description': '高度な機能と競争力のある手数料で完璧な取引プランを選択してください',
    'cta.title': '取引を始める準備はできましたか？',
    'cta.description': '私たちのプラットフォームの力をすでに発見した何千ものトレーダーに参加してください。',
    'cta.button': 'アカウント作成',
    'pricing.basic.name': 'ベーシックトレーダー',
    'pricing.basic.description': '暗号通貨の旅を始める初心者に最適',
    'pricing.pro.name': 'プロトレーダー',
    'pricing.pro.description': '本格的なトレーダー向けの高度な機能',
    'pricing.institutional.name': '機関投資家',
    'pricing.institutional.description': '機関向けエンタープライズグレードソリューション',
    'pricing.popular': '最も人気',
    'pricing.startTrading': '取引開始',
    'pricing.basic.feature1': 'ベーシックスポット取引',
    'pricing.basic.feature2': '成行・指値注文',
    'pricing.basic.feature3': 'ベーシック市場分析',
    'pricing.basic.feature4': 'メールサポート',
    'pricing.pro.feature1': '高度な取引ツール',
    'pricing.pro.feature2': '最大10倍のマージン取引',
    'pricing.pro.feature3': '高度なテクニカル分析',
    'pricing.pro.feature4': '優先サポート',
    'pricing.pro.feature5': 'APIアクセス',
    'pricing.institutional.feature1': 'カスタム取引ソリューション',
    'pricing.institutional.feature2': '無制限の取引ボリューム',
    'pricing.institutional.feature3': 'OTCデスクアクセス',
    'pricing.institutional.feature4': '専任アカウントマネージャー',
    'pricing.institutional.feature5': 'カスタムAPI統合',
    'pricing.institutional.feature6': '24/7優先サポート',
    'testimonials.title': 'トレーダーに信頼されています',
    'testimonials.subtitle': 'CryptoTradeで数千人の満足したトレーダーに参加してください',
    'testimonials.michael.role': 'プロフェッショナルトレーダー',
    'testimonials.michael.content': 'リアルタイムの市場データと高度な取引機能により、私の取引パフォーマンスが大幅に向上しました。プラットフォームのセキュリティ対策により安心できます。',
    'testimonials.sarah.role': '暗号通貨ファンドマネージャー',
    'testimonials.sarah.content': 'CryptoTradeの機関レベルのツールにより、私たちの取引戦略が変革しました。API統合と自動化機能により、無数の時間を節約できました。',
    'testimonials.david.role': '初期暗号通貨投資家',
    'testimonials.david.content': 'カスタマーサポートは素晴らしく、プラットフォームの直感的なデザインにより暗号通貨取引の開始がスムーズでした。初心者とプロの両方にとってゲームチェンジャーです。',
    'testimonials.emily.role': 'DeFi開発者',
    'testimonials.emily.content': 'CryptoTradeに切り替えてから、取引効率の顕著な改善を見ています。スマートオーダールーティングと流動性集約が特に印象的です。',
    'testimonials.james.role': '暗号通貨セキュリティ専門家',
    'testimonials.james.content': 'セキュリティ機能は堅牢で、定期的なアップデートにより新たな脅威に先手を打っています。暗号通貨業界が必要としていたものそのものです。',
    'testimonials.lisa.role': 'ポートフォリオマネージャー',
    'testimonials.lisa.content': '複雑な取引戦略を処理しながらインターフェースのシンプルさを維持するプラットフォームの能力は素晴らしいです。私たちのポートフォリオ管理にとってかけがえのないものでした。',
    'signup.backToHome': 'ホームに戻る',
    'signup.title': 'アカウントを作成',
    'signup.subtitle': 'CryptoTradeで数千人のトレーダーに参加',
    'signup.firstName': '名',
    'signup.lastName': '姓',
    'signup.email': 'メールアドレス',
    'signup.password': 'パスワード',
    'signup.firstNamePlaceholder': '名前を入力',
    'signup.lastNamePlaceholder': '姓を入力',
    'signup.emailPlaceholder': 'メールアドレスを入力',
    'signup.passwordPlaceholder': '強力なパスワードを作成',
    'signup.createAccount': 'アカウント作成',
    'signup.alreadyHaveAccount': 'すでにアカウントをお持ちですか？',
    'signup.signIn': 'サインイン',
    'login.backToHome': 'ホームに戻る',
    'login.title': 'おかえりなさい',
    'login.subtitle': 'CryptoTradeアカウントにサインイン',
    'login.email': 'メールアドレス',
    'login.password': 'パスワード',
    'login.emailPlaceholder': 'メールアドレスを入力',
    'login.passwordPlaceholder': 'パスワードを入力',
    'login.forgotPassword': 'パスワードを忘れましたか？',
    'login.signIn': 'サインイン',
    'login.noAccount': 'アカウントをお持ちでないですか？',
    'login.createAccount': 'アカウント作成',
    'markets.backToHome': 'ホームに戻る',
    'markets.title': '暗号通貨',
    'markets.titleHighlight': 'マーケット',
    'markets.subtitle': 'リアルタイムの暗号通貨価格と市場データ',
    'markets.searchPlaceholder': '暗号通貨を検索...',
    'markets.coin': 'コイン',
    'markets.price': '価格',
    'markets.change24h': '24時間変化',
    'markets.volume': 'ボリューム',
    'markets.marketCap': '時価総額',
    'markets.action': 'アクション',
    'markets.trade': '取引',
    'markets.ctaTitle': '取引を始める準備はできましたか？',
    'markets.ctaDescription': '数千人のトレーダーに参加し、今日から暗号通貨の旅を始めましょう',
    'markets.startTrading': '今すぐ取引開始'
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('cryptotrade-language');
    return (saved as Language) || 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('cryptotrade-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[Language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};