import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'en' | 'fr' | 'de' | 'it' | 'pt' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Sobre Mí',
    'nav.services': 'Servicios',
    'nav.contact': 'Contacto',
    'hero.title': 'Desarrollador Full Stack',
    'hero.subtitle': 'Transformo ideas en aplicaciones web exitosas. Especialista en crear experiencias digitales que impulsan negocios y conectan con usuarios reales.',
    'hero.viewProjects': 'Ver Proyectos',
    'hero.contact': 'Contáctame',
    'hero.frontend': 'React, TypeScript, Tailwind CSS para crear interfaces modernas y responsivas.',
    'hero.backend': 'Node.js, Express, bases de datos para crear APIs robustas y escalables.',
    'hero.ecommerce': 'Experiencia en tiendas online, sistemas de pago y gestión de inventarios.',
    'projects.title': 'Mis Proyectos de E-commerce',
    'projects.subtitle': 'Explora los proyectos web que he desarrollado, desde e-commerce hasta plataformas fintech, cada uno con tecnologías modernas y funcionalidades completas.',
    'projects.learnMore': 'Learn more',
    'features.title': 'Como desarrollador full stack junior, domino tecnologías modernas para crear aplicaciones web completas, desde el frontend hasta el backend y bases de datos.',
    'features.frontend.title': 'Frontend Development',
    'features.frontend.desc': 'Desarrollo de interfaces modernas y responsivas con React, TypeScript, Tailwind CSS y Next.js para crear experiencias de usuario excepcionales.',
    'features.backend.title': 'Backend Development', 
    'features.backend.desc': 'Creación de APIs robustas y escalables con Node.js, Express, bases de datos SQL y NoSQL para aplicaciones web completas.',
    'features.ecommerce.title': 'E-commerce Solutions',
    'features.ecommerce.desc': 'Especialización en desarrollo de tiendas online con sistemas de pago, gestión de inventarios y paneles de administración.',
    'features.fullstack.title': 'Full Stack Integration',
    'features.fullstack.desc': 'Integración completa de frontend y backend, deployment en la nube y optimización de rendimiento para aplicaciones escalables.',
    'whywrlds.title': 'Stack Tecnológico',
    'whywrlds.subtitle': 'Tecnologías que Domino',
    'whywrlds.description': 'Explora las principales tecnologías que utilizo en mis proyectos, desde frameworks frontend hasta bases de datos y herramientas de desarrollo.',
    'contact.title': 'Contáctame',
    'contact.subtitle': '¿Tienes un proyecto en mente? Contáctame y hablemos sobre cómo puedo ayudarte a crear soluciones web innovadoras.',
    'contact.name': 'Jesús Eliud Soto Méndez',
    'contact.role': 'Desarrollador Full Stack Junior',
    'tech.swipe': 'Desliza horizontalmente para ver más ejemplos →',
    'tech.react.title': 'React & TypeScript',
    'tech.react.desc': 'Desarrollo de aplicaciones web modernas con React, TypeScript y hooks para crear interfaces dinámicas y mantenibles.',
    'tech.node.title': 'Node.js & Express',
    'tech.node.desc': 'Creación de APIs REST y GraphQL con Node.js, Express y middleware personalizado para aplicaciones escalables.',
    'tech.db.title': 'Bases de Datos',
    'tech.db.desc': 'Experiencia con MongoDB, PostgreSQL y MySQL para diseño de esquemas y optimización de consultas.',
    'tech.devops.title': 'DevOps & Deploy',
    'tech.devops.desc': 'Deployment en AWS, Docker, CI/CD con GitHub Actions para automatización y escalabilidad.',
    'tech.testing.title': 'Testing & QA',
    'tech.testing.desc': 'Jest, Cypress, testing unitario e integración para garantizar calidad del código.',
    'tech.analytics.title': 'Analytics & SEO',
    'tech.analytics.desc': 'Google Analytics, SEO optimization y performance monitoring para mejores resultados.',
    'methodology.title': 'Cómo trabajo en mis proyectos',
    'methodology.subtitle': 'Utilizo metodologías ágiles y las mejores prácticas de desarrollo para crear aplicaciones web robustas, escalables y mantenibles con tecnologías modernas.',
    'methodology.planning.title': 'Planificación y Diseño',
    'methodology.planning.desc': 'Análisis de requerimientos y diseño de arquitectura escalable',
    'methodology.agile.title': 'Desarrollo Ágil',
    'methodology.agile.desc': 'Implementación iterativa con metodologías ágiles y buenas prácticas',
    'methodology.testing.title': 'Testing y Deploy',
    'methodology.testing.desc': 'Pruebas exhaustivas y despliegue en producción con CI/CD',
    'methodology.project.title': 'Proyecto de Desarrollo',
    'methodology.iterative.title': 'Desarrollo Iterativo',
    'methodology.iterative.desc': 'Trabajo de forma iterativa para entregar valor continuo y adaptarme a los cambios',
    'methodology.phases.planning': 'Planificación',
    'methodology.phases.development': 'Desarrollo',
    'methodology.phases.testing': 'Testing',
    'methodology.phases.review': 'Revisión',
    'methodology.feedback': 'Feedback continuo integrado en cada etapa',
    'methodology.improvement': 'Mejora continua',
    'methodology.ready.title': 'Listo para Producir',
    'methodology.ready.desc': 'Preparado para escalar, optimizar y lanzar',
    'about.title': 'Sobre Mí',
    'about.subtitle': 'Desarrollador Full Stack especializado en transformar ideas en aplicaciones web exitosas que generan resultados reales',
    'about.months': '1 año',
    'about.months.desc': 'Experiencia desarrollando aplicaciones que han impactado positivamente a usuarios reales',
    'about.projects': '8+ proyectos',
    'about.projects.desc': 'Aplicaciones web completas desde e-commerce hasta fintech, todas en producción y funcionando',
    'about.technologies': '15+ tecnologías',
    'about.technologies.desc': 'Stack moderno completo: React, Node.js, TypeScript, bases de datos, AWS y más',
    'about.contribute.title': 'Mi Pasión por la Excelencia',
    'about.contribute.subtitle': 'No solo escribo código, creo experiencias digitales que conectan con los usuarios y generan valor real para los negocios',
    'about.modern.title': 'Innovación Constante',
    'about.modern.desc': 'Siempre actualizado con las últimas tecnologías y tendencias. Mi código no solo funciona, es escalable y mantenible.',
    'about.learning.title': 'Solucionador de Problemas',
    'about.learning.desc': 'Cada desafío es una oportunidad. Transformo problemas complejos en soluciones elegantes y eficientes.',
    'about.complete.title': 'Resultados Comprobados',
    'about.complete.desc': 'Mis aplicaciones no solo se ven bien, funcionan perfectamente y han ayudado a negocios a crecer y prosperar.',
    'about.commitment.title': 'Compromiso Total',
    'about.commitment.desc': 'Tu éxito es mi éxito. Me comprometo al 100% con cada proyecto hasta lograr resultados excepcionales.',
    'about.contact': 'Hablemos sobre cómo puedo impulsar tu próximo proyecto',
    'project.fashion.title': 'Tienda de Ropa Online',
    'project.fashion.brand': 'Fashion Store',
    'project.fashion.desc': 'E-commerce completo para tienda de ropa con catálogo de productos, carrito de compras, sistema de pagos y panel de administración.',
    'project.gym.title': 'Tienda de Suplementos',
    'project.gym.brand': 'Gym Supplements',
    'project.gym.desc': 'Plataforma de venta de suplementos deportivos con sistema de recomendaciones y seguimiento de pedidos.',
    'project.bookstore.title': 'Librería Online',
    'project.bookstore.brand': 'BookStore Digital',
    'project.bookstore.desc': 'Sistema de venta de libros digitales y físicos con búsqueda avanzada, reseñas de usuarios y sistema de recomendaciones.',
    'project.crypto.title': 'Plataforma Crypto',
    'project.crypto.brand': 'CryptoTrade',
    'project.crypto.desc': 'Aplicación para seguimiento de criptomonedas con gráficos en tiempo real, portfolio personal y alertas de precios.',
    'project.tech.title': 'E-commerce Electrónicos',
    'project.tech.brand': 'TechStore',
    'project.tech.desc': 'Tienda online de productos electrónicos con comparador de precios, especificaciones técnicas y sistema de garantías.',
    'pricing.title': 'Planes y Precios',
    'pricing.subtitle': 'Elige el plan que mejor se adapte a tu proyecto. Todos incluyen código limpio, diseño responsive y soporte post-entrega.',
    'pricing.popular': 'Más Popular',
    'pricing.start': 'Comenzar Proyecto',
    'pricing.custom': '¿Necesitas algo personalizado?',
    'pricing.quote': 'Solicitar Cotización Personalizada',
    'tech.footer': 'Estas son algunas de las tecnologías principales que utilizo en mis proyectos de desarrollo web',
    'buttons.needDev': '¿Necesitas un Desarrollador?',
    'buttons.moreSkills': 'Ver Más Sobre Mis Habilidades'
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Me',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'hero.title': 'Full Stack Developer',
    'hero.subtitle': 'I transform ideas into successful web applications. Specialist in creating digital experiences that drive businesses and connect with real users.',
    'hero.viewProjects': 'View Projects',
    'hero.contact': 'Contact Me',
    'hero.frontend': 'React, TypeScript, Tailwind CSS to create modern and responsive interfaces.',
    'hero.backend': 'Node.js, Express, databases to create robust and scalable APIs.',
    'hero.ecommerce': 'Experience in online stores, payment systems and inventory management.',
    'projects.title': 'My Web Projects',
    'projects.subtitle': 'Explore the web projects I have developed, from e-commerce to fintech platforms, each with modern technologies and complete functionalities.',
    'projects.learnMore': 'Learn more',
    'features.title': 'As a junior full stack developer, I master modern technologies to create complete web applications, from frontend to backend and databases.',
    'features.frontend.title': 'Frontend Development',
    'features.frontend.desc': 'Development of modern and responsive interfaces with React, TypeScript, Tailwind CSS and Next.js to create exceptional user experiences.',
    'features.backend.title': 'Backend Development',
    'features.backend.desc': 'Creation of robust and scalable APIs with Node.js, Express, SQL and NoSQL databases for complete web applications.',
    'features.ecommerce.title': 'E-commerce Solutions',
    'features.ecommerce.desc': 'Specialization in online store development with payment systems, inventory management and administration panels.',
    'features.fullstack.title': 'Full Stack Integration',
    'features.fullstack.desc': 'Complete frontend and backend integration, cloud deployment and performance optimization for scalable applications.',
    'whywrlds.title': 'Technology Stack',
    'whywrlds.subtitle': 'Technologies I Master',
    'whywrlds.description': 'Explore the main technologies I use in my projects, from frontend frameworks to databases and development tools.',
    'contact.title': 'Contact Me',
    'contact.subtitle': 'Do you have a project in mind? Contact me and let\'s talk about how I can help you create innovative web solutions.',
    'contact.name': 'Jesús Eliud Soto Méndez',
    'contact.role': 'Junior Full Stack Developer',
    'tech.swipe': 'Swipe horizontally to see more examples →',
    'tech.react.title': 'React & TypeScript',
    'tech.react.desc': 'Development of modern web applications with React, TypeScript and hooks to create dynamic and maintainable interfaces.',
    'tech.node.title': 'Node.js & Express',
    'tech.node.desc': 'Creation of REST and GraphQL APIs with Node.js, Express and custom middleware for scalable applications.',
    'tech.db.title': 'Databases',
    'tech.db.desc': 'Experience with MongoDB, PostgreSQL and MySQL for schema design and query optimization.',
    'tech.devops.title': 'DevOps & Deploy',
    'tech.devops.desc': 'Deployment on AWS, Docker, CI/CD with GitHub Actions for automation and scalability.',
    'tech.testing.title': 'Testing & QA',
    'tech.testing.desc': 'Jest, Cypress, unit and integration testing to ensure code quality.',
    'tech.analytics.title': 'Analytics & SEO',
    'tech.analytics.desc': 'Google Analytics, SEO optimization and performance monitoring for better results.',
    'methodology.title': 'How I work on my projects',
    'methodology.subtitle': 'I use agile methodologies and development best practices to create robust, scalable and maintainable web applications with modern technologies.',
    'methodology.planning.title': 'Planning and Design',
    'methodology.planning.desc': 'Requirements analysis and scalable architecture design',
    'methodology.agile.title': 'Agile Development',
    'methodology.agile.desc': 'Iterative implementation with agile methodologies and best practices',
    'methodology.testing.title': 'Testing and Deploy',
    'methodology.testing.desc': 'Comprehensive testing and production deployment with CI/CD',
    'methodology.project.title': 'Development Project',
    'methodology.iterative.title': 'Iterative Development',
    'methodology.iterative.desc': 'I work iteratively to deliver continuous value and adapt to changes',
    'methodology.phases.planning': 'Planning',
    'methodology.phases.development': 'Development',
    'methodology.phases.testing': 'Testing',
    'methodology.phases.review': 'Review',
    'methodology.feedback': 'Continuous feedback integrated at each stage',
    'methodology.improvement': 'Continuous improvement',
    'methodology.ready.title': 'Ready to Produce',
    'methodology.ready.desc': 'Prepared to scale, optimize and launch',
    'about.title': 'About Me',
    'about.subtitle': 'Full Stack Developer specialized in transforming ideas into successful web applications that generate real results',
    'about.months': '1 year',
    'about.months.desc': 'Experience developing applications that have positively impacted real users',
    'about.projects': '8+ projects',
    'about.projects.desc': 'Complete web applications from e-commerce to fintech, all in production and working',
    'about.technologies': '15+ technologies',
    'about.technologies.desc': 'Complete modern stack: React, Node.js, TypeScript, databases, AWS and more',
    'about.contribute.title': 'My Passion for Excellence',
    'about.contribute.subtitle': 'I don\'t just write code, I create digital experiences that connect with users and generate real value for businesses',
    'about.modern.title': 'Constant Innovation',
    'about.modern.desc': 'Always updated with the latest technologies and trends. My code doesn\'t just work, it\'s scalable and maintainable.',
    'about.learning.title': 'Problem Solver',
    'about.learning.desc': 'Every challenge is an opportunity. I transform complex problems into elegant and efficient solutions.',
    'about.complete.title': 'Proven Results',
    'about.complete.desc': 'My applications don\'t just look good, they work perfectly and have helped businesses grow and prosper.',
    'about.commitment.title': 'Total Commitment',
    'about.commitment.desc': 'Your success is my success. I commit 100% to each project until achieving exceptional results.',
    'about.contact': 'Let\'s talk about how I can boost your next project',
    'project.fashion.title': 'Online Clothing Store',
    'project.fashion.brand': 'Fashion Store',
    'project.fashion.desc': 'Complete e-commerce for clothing store with product catalog, shopping cart, payment system and administration panel.',
    'project.gym.title': 'Supplements Store',
    'project.gym.brand': 'Gym Supplements',
    'project.gym.desc': 'Sports supplements sales platform with recommendation system and order tracking.',
    'project.bookstore.title': 'Online Bookstore',
    'project.bookstore.brand': 'BookStore Digital',
    'project.bookstore.desc': 'Digital and physical book sales system with advanced search, user reviews and recommendation system.',
    'project.crypto.title': 'Crypto Platform',
    'project.crypto.brand': 'CryptoTrade',
    'project.crypto.desc': 'Application for cryptocurrency tracking with real-time charts, personal portfolio and price alerts.',
    'project.tech.title': 'Electronics E-commerce',
    'project.tech.brand': 'TechStore',
    'project.tech.desc': 'Online store for electronic products with price comparator, technical specifications and warranty system.',
    'pricing.title': 'Plans and Pricing',
    'pricing.subtitle': 'Choose the plan that best fits your project. All include clean code, responsive design and post-delivery support.',
    'pricing.popular': 'Most Popular',
    'pricing.start': 'Start Project',
    'pricing.custom': 'Need something custom?',
    'pricing.quote': 'Request Custom Quote',
    'tech.footer': 'These are some of the main technologies I use in my web development projects',
    'buttons.needDev': 'Need a Developer?',
    'buttons.moreSkills': 'Learn More About My Skills'
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.projects': 'Projets',
    'nav.contact': 'Contact',
    'hero.title': 'Développeur Full Stack Junior',
    'hero.subtitle': 'Diplômé il y a 2 mois avec 5 projets e-commerce développés et passion pour créer des solutions web innovantes.',
    'hero.viewProjects': 'Voir Projets',
    'hero.contact': 'Me Contacter'
  },
  de: {
    'nav.home': 'Startseite',
    'nav.about': 'Über Mich',
    'nav.projects': 'Projekte',
    'nav.contact': 'Kontakt',
    'hero.title': 'Junior Full Stack Entwickler',
    'hero.subtitle': 'Vor 2 Monaten abgeschlossen mit 5 entwickelten E-Commerce-Projekten und Leidenschaft für innovative Web-Lösungen.',
    'hero.viewProjects': 'Projekte Ansehen',
    'hero.contact': 'Kontaktiere Mich'
  },
  it: {
    'nav.home': 'Home',
    'nav.about': 'Chi Sono',
    'nav.projects': 'Progetti',
    'nav.contact': 'Contatto',
    'hero.title': 'Sviluppatore Full Stack Junior',
    'hero.subtitle': 'Laureato 2 mesi fa con 5 progetti e-commerce sviluppati e passione per creare soluzioni web innovative.',
    'hero.viewProjects': 'Vedi Progetti',
    'hero.contact': 'Contattami'
  },
  pt: {
    'nav.home': 'Início',
    'nav.about': 'Sobre Mim',
    'nav.projects': 'Projetos',
    'nav.contact': 'Contato',
    'hero.title': 'Desenvolvedor Full Stack Júnior',
    'hero.subtitle': 'Formado há 2 meses com 5 projetos e-commerce desenvolvidos e paixão por criar soluções web inovadoras.',
    'hero.viewProjects': 'Ver Projetos',
    'hero.contact': 'Entre em Contato'
  },
  zh: {
    'nav.home': '首页',
    'nav.about': '关于我',
    'nav.projects': '项目',
    'nav.contact': '联系',
    'hero.title': '初级全栈开发者',
    'hero.subtitle': '两个月前毕业，已开发5个电商项目，热衷于创建创新的网络解决方案。',
    'hero.viewProjects': '查看项目',
    'hero.contact': '联系我'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[Language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};